server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zdw19991027@
    url: jdbc:mysql://127.0.0.1:3306/takeaway?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      #mail
      #发送邮件

  mail:
  #    protocol: smtps
  protocol: smtp
  # 配置 SMTP 服务器地址
  host: smtp.qq.com
  # 发送者邮箱
  #    username: xqnode@163.com
  username: 1938976892@qq.com
  # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
  password: xxx
  # 端口号465或587
  #    port: 465
  port: 587
  # 默认的邮件编码为UTF-8
  default-encoding: UTF-8



# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #驼峰属性配置

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost

